### ISSUE TITLE
Livereload should be put back in gulpfile

### ISSUE THREAD

**Issue by jeroenransijn** [AanZee/harbour#18]
When I transferred some code from a project specific gulpfile to the Harbour gulpfile, I accidentally removed all livereload logic. This should be set back, maybe optionally through a setting. Could be done with `gulp-if` quite easily.

**Comment by jellekralt** [comment]
Why would you want this to be optional (through a setting)?

**Comment by jeroenransijn** [comment]
I figured live reload might not work when working on a server.

**Comment by edgargressie** [comment]
We can add a setting for remote servers. So we can make more optional functions in the future

**Comment by jellekralt** [comment]
SGTM

**Comment by edgargressie** [comment]
https://github.com/AanZee/harbour/pull/20
