### ISSUE TITLE
Messages, alerts and notifications styling

### ISSUE THREAD

**Issue by jeroenransijn** [AanZee/harbour#8]
I would like to propose creating 3 types of messages: messages, alerts and notifications. Bootstrap uses the class `.alert` [for it's message](http://getbootstrap.com/components/#alerts). This is because of the `role="alert"` [ARIA accessibility attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role). However, the styling of the messages in Bootstrap are quite big, and not as compact as the form validation messages seen in [FixMeStick](http://www.fixmestick.eu/order). I want to suggest to divide messages into 3 groups:
## Alerts
- Used inside forms 
- Make use of the `role="alert"` attribute
- Are often visually coupled to an input field with an arrow pointing up
- Colour coded

``` html
<div class="alert alert--point-up alert--danger" role="alert">Your name is required</div>
```
## Messages
- Messages are used as a more  bigger type of notification 
- Bound to a certain piece of content on the page
- Not restricted to the use in forms
- Colour coded
- May use the `role="alert"` attribute when applicable
- May be dismissible  

``` html
<div class="message message--info">
    Lorem ipsum...
   <!-- close button copied from bootstrap as an example -->
    <button type="button" class="message__close" data-dismiss="alert">Close</button>
</div>
```
## Notifications
- Often site wide and not bound to a certain piece of content E.G. cookie notifications
- Often fixed or absolutely positioned
- May use the `role="alert"` attribute when applicable
- May be dismissible 

``` html
<div class="notification">
    Lorem ipsum...
    <button type="button" class="notification__close" data-dismiss="alert">Accepteer cookies</button>
</div>
```

**Note:** wether or not the functional name will be  `danger` is not important to this issue. I've stuck with the colours used by Bootstrap: `success`/``warning`/`info`/`danger`.

Suggestions and feedback are welcome.

**Comment by bartvandebiezen** [comment]
**Alerts**: other notifications can also be alerts (i.e. role='alert'). This could be confusing.
**Messages**: other components can also be messages, such as chat messages. Or is a message the content of a notification?

Others also use: help, or feedback. OS X calls everything a notification. I think this is a good idea. We could create different types of notifications, the same way we create different headers (e.g. page-header) and footers (e.g. page-footer). Also, they see 'badges' as notifications. We could use the following list:

- notification
- badge-notification
- input-notification
- page-notification

**Comment by jeroenransijn** [comment]
The usage of `input-notification` has been part of the discussion I had with @edgargressie. In most cases this type of notification will be paired with an `input` element. However, it might also be paired to elements which do not use the `input` tag, such as `textarea`, `select`, `radio` and possibly custom input times. Using the name `input-notification` might confuse developers into thinking it is only suited for coupling to an `input` element.

Another concern I have is about what the default class `notification` will be used for. In addition, `badge-notification` is also an odd one in the list since it refers to the the form of the notification instead of the functional usage. Can a `page-notification` be a `badge`? The term `badge` might be more useful as a modifier in that case.

How would you describe `page-noticiation`? Are this notifications bound to the page, or can this notifications be site wide such as the cookie notification?

The main pro of having distinctive names for different types of notifications are to avoid confusion. Alerts are described by MDN as:
> The alert role is used to communicate an important and usually time-sensitive message to the user
