### ISSUE TITLE
Colour codes for messages, alerts etc.

### ISSUE THREAD

**Issue by jeroenransijn** [AanZee/harbour#9]
Bootstrap uses `success`/`info`/`warning`/`danger` to colour code certain elements:

``` html
<div class="alert alert-success" role="alert">...</div>
<div class="alert alert-info" role="alert">...</div>
<div class="alert alert-warning" role="alert">...</div>
<div class="alert alert-danger" role="alert">...</div>
```

I suggest to have support these colour codes of the box as color variables inside the `settings` folder:

``` scss
$color-success: ;
$color-info: ;
$color-warning: ;
$color-danger: ;
```

Although I am not quite sure about the names, especially `danger` and `warning` are confusing. Some name to consider are:
- note
- error
- success
- info
- warning
- danger

**Comment by bartvandebiezen** [comment]
Also not a fan of 'note' or 'info' because they are not very specific. Everything is information. Perhaps linking color name and state name?

**Comment by jeroenransijn** [comment]
Could you clarify what you mean by the linking color and state name? It should be noted that notifications are not concerned with state, they haven't got a `is-valid` state for example. Colours could make use of state names, but this can only go so far and still make sense in my opinion:
```
$color-valid: ;
$color-invalid: ;
```

Maybe `info` and `note` are not the correct words, but in a lot of use cases a default (often yellow) message makes it appearance. It is more important to me to have this colour available than to discard it because of it's name.  I would suggest to use `note`/`info` unless someone can come up with a more suitable name.
